# Generated by Django 2.2.28 on 2023-09-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '商家'), (3, '超级管理')], default=1, verbose_name='角色'),
        ),
    ]
